tags:
  - mmnn

valid_size: 0.2

quantile_transform: 'normal'

n_quantiles: 100

clip_rooms: null

im_size: !!python/tuple [64,64]

save: False

model_params:
  max_epochs: 1
  patience: 1
  batch_size: 128
  predict_batch_size: 256
  lr: 0.02
  lr_patience: 50
  lr_factor: 0.1
  max_lr: 0.04
  weight_decay: 0.00001
  hidden_size: 8